import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'en' | 'kk';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    ru: {
        'nav.dashboard': 'Дашборд',
        'nav.ocr': 'Проверка работ',
        'nav.ai': 'AI Ассистент',
        'nav.files': 'Библиотека файлов',
        'nav.library': 'Библиотека тестов',
        'nav.results': 'Результаты',
        'nav.analytics': 'Аналитика',
        'nav.settings': 'Настройки',
        'nav.support': 'Поддержка',
        'nav.logout': 'Выйти',
        'nav.tools': 'Инструменты учителя',
        'nav.saved': 'сэкономлено с ИИ',
        'nav.myDashboard': 'Мой кабинет',
        'nav.myProgress': 'Мой прогресс',
        'nav.myAssignments': 'Мои задания',
        'nav.myTests': 'Мои тесты',
        'nav.assignments': 'Задания',
        'nav.studentDashboard': 'Кабинет ученика',
        'nav.loading': 'Загрузка...',
        'nav.noCourses': 'Нет курсов',
        'nav.createCourse': 'Создать курс',
        
        'dash.welcome': 'Доброе утро',
        'dash.upload': 'Загрузить материал',
        'dash.check': 'Проверить работы',
        'dash.needsReview': 'Требует проверки',
        'dash.viewAll': 'Смотреть все',
        'dash.performance': 'Успеваемость класса',
        'dash.avgScore': 'Средний балл',
        'dash.activity': 'Недавняя активность',
        'dash.search': 'Поиск по материалам...',
        'dash.export': 'Экспорт',
        'dash.queue': 'Очередь загрузки',
        'dash.clear': 'Очистить',
        
        'ocr.back': 'Назад',
        'ocr.save': 'Сохранить',
        'ocr.confirmAll': 'Подтвердить все',
        'ocr.unsaved': 'Не сохранено',
        'ocr.accuracy': 'Точность',
        'ocr.selected': 'выбрано',
        'ocr.approveSelected': 'Подтвердить выбранные',
        'ocr.close': 'Закрыть',
        'ocr.saveChanges': 'Сохранить изменения',
        'ocr.th.student': 'Студент',
        'ocr.th.subject': 'Предмет',
        'ocr.th.accuracy': 'Точность',
        'ocr.th.status': 'Статус',
        'ocr.th.actions': 'Действия',
        'ocr.review': 'Проверить',
        'ocr.grade': 'Оценка',
        'ocr.caughtUp': 'Все проверено! Нет ожидающих работ.',
        'ocr.allChecked': 'Все проверено!',
        'ocr.reviewMode': 'ПРОВЕРКА',
        'ocr.autoRecognized': 'Система автоматически распознала текст с изображений. Проверьте точность и утвердите оценки.',
        'ocr.noSubject': 'Без предмета',
        'ocr.status.flagged': 'требует внимания',
        'ocr.status.reviewing': 'на проверке',
        'ocr.conf.high': 'Высокая точность',
        'ocr.conf.low': 'Низкая точность',
        
        'ai.typing': 'печатает...',
        'ai.ask': 'Спросить ИИ',
        'ai.analysis': 'Анализ',
        'ai.history': 'История сессий',
        'ai.newChat': 'Новый чат',
        'ai.placeholder': 'Задайте вопрос по материалу...',
        'ai.tab.canvas': 'AI Холст',
        'ai.tab.builder': 'Конструктор тестов',
        'ai.actions': 'Действия ИИ',
        'ai.action.explain': 'Объяснить',
        'ai.action.simplify': 'Упростить',
        'ai.action.translate': 'Перевести',
        'ai.difficulty': 'СЛОЖНОСТЬ',
        'ai.count': 'КОЛИЧЕСТВО',
        'ai.generate': 'Сгенерировать',
        'ai.generating': 'Генерация...',
        'ai.explanation': 'Объяснение',
        'ai.diff.easy': 'Легкий',
        'ai.diff.medium': 'Средний',
        'ai.diff.hard': 'Сложный',

        'analytics.title': 'Аналитика класса',
        'analytics.subtitle': 'Детальный обзор успеваемости',
        'analytics.average': 'Средний балл',
        'analytics.leaderboard': 'Рейтинг учеников',
        'analytics.back': 'Назад к обзору',
        'analytics.breakdown': 'Разбор по ученикам',

        'settings.title': 'Настройки',
        'settings.subtitle': 'Управление профилем и предпочтениями',
        'settings.profile': 'Профиль',
        'settings.name': 'Имя',
        'settings.surname': 'Фамилия',
        'settings.email': 'Email',
        'settings.emailReports': 'Email отчеты',
        'settings.notifications': 'Умные уведомления',
        'settings.language': 'Язык интерфейса',
        'settings.demo': 'Демо режим',
        'settings.demoDesc': 'Сброс очистит все локальные изменения и восстановит исходные данные.',
        'settings.reset': 'Сбросить данные к демо-версии',
        'settings.save': 'Сохранить',
        'settings.cancel': 'Отмена',

        'auth.register': 'Регистрация',
        'auth.createAccount': 'Создать аккаунт',
        'auth.firstName': 'Имя',
        'auth.lastName': 'Фамилия',
        'auth.password': 'Пароль',
        'auth.alreadyHaveAccount': 'Уже есть аккаунт?',
        'auth.login': 'Войти',
        'auth.join': 'Присоединиться',

        // Login
        'login.title': 'Вход в систему',
        'login.subtitle': 'Введите свои данные для доступа',
        'login.invalidEmail': 'Введите корректный Email',
        'login.enterPassword': 'Введите пароль',
        'login.forgotPassword': 'Забыли пароль?',
        'login.welcome': 'Добро пожаловать!',
        'login.invalidCredentials': 'Неверный логин или пароль',
        'login.noAccount': 'Еще нет аккаунта?',

        // Teacher Quiz Preview
        'preview.title': 'Предпросмотр теста',
        'preview.subtitle': 'Режим учителя: редактирование перед отправкой ученикам.',
        'preview.backToAI': 'Назад в AI',
        'preview.saveChanges': 'Сохранить изменения',
        'preview.saving': 'Сохранение...',
        'preview.quizTitle': 'Название теста',
        'preview.test': 'Тест',
        'preview.failedToLoad': 'Не удалось загрузить тест',
        'preview.changesSaved': 'Изменения сохранены',
        'preview.failedToSave': 'Не удалось сохранить изменения',

        // Settings additional
        'settings.drawnAvatars': 'Нарисованные аватары',
        'settings.selectAvatar': 'Выбрать аватар',
        'settings.importAvatar': 'Импорт аватара',
        'settings.failedToLoadProfile': 'Не удалось загрузить профиль пользователя',
        'settings.onlyImages': 'Можно импортировать только изображения',
        'settings.avatarImported': 'Аватар импортирован',
        'settings.failedToImportAvatar': 'Не удалось импортировать аватар',
        'settings.errorSaving': 'Ошибка при сохранении профиля',

        // Register
        'register.validEmail': 'Пожалуйста, введите корректный рабочий email',
        'register.passwordLength': 'Пароль должен быть не менее 6 символов',
        'register.accountCreated': 'Аккаунт создан успешно! Теперь войдите.',

        // OCR
        'ocr.fileNotFound': 'Файл не найден',
        'ocr.failedToLoadQueue': 'Не удалось загрузить очередь OCR',
        'ocr.failedToLoadDetails': 'Не удалось загрузить детали работы',
        'ocr.batchFailed': 'Пакетная операция не выполнена',
        'ocr.changesSaved': 'Изменения сохранены',
        'ocr.failedToSave': 'Не удалось сохранить',

        // Materials Library
        'materials.linkCreated': 'Ссылка и код задания созданы',
        'materials.failedToCreateLink': 'Не удалось создать ссылку задания',
        'materials.codeCopied': 'Код скопирован',
        'materials.linkCopied': 'Ссылка скопирована',
        'materials.title': 'Библиотека файлов',
        'materials.courseFiles': 'Файлы курса',
        'materials.backToDashboard': 'На дашборд',
        'materials.searchPlaceholder': 'Поиск материала...',
        'materials.noCourseSelected': 'курс не выбран',
        'materials.selectCourseFirst': 'Сначала выберите курс в левом меню',
        'materials.loading': 'Загрузка...',
        'materials.notFound': 'Материалы не найдены',
        'materials.publishedCount': 'Опубликованных заданий',
        'materials.clearLinks': 'Очистить сохранённые ссылки',
        'materials.published': 'Задание опубликовано',
        'materials.openAsStudent': 'Открыть как ученик',
        'materials.copyCode': 'Копировать код',
        'materials.copyLink': 'Копировать ссылку',
        'materials.creating': 'Создаю...',
        'materials.updateLink': 'Обновить ссылку',
        'materials.createAssignment': 'Создать задание',
        'materials.openInAI': 'Открыть в AI',
        'materials.failedToLoad': 'Не удалось загрузить библиотеку материалов',

        // Analytics
        'analytics.preparingPDF': 'Подготовка PDF...',
        'analytics.reportReady': 'Отчет готов к печати',
        'analytics.noCourseSelected': 'Выберите курс для просмотра аналитики',
        'analytics.noDataTitle': 'Нет данных для отображения',
        'analytics.noDataDesc': 'Загрузите материалы и создайте тесты',
        'analytics.exportPdf': 'Экспорт PDF',
        'analytics.regularStudentsTitle': 'Постоянные ученики',
        'analytics.regularStudentsDesc': '3+ выполненных теста в курсе',
        'analytics.activeStudentsTitle': 'Всего активных',
        'analytics.activeStudentsDesc': 'учеников с результатами',
        'analytics.howToBecomeRegularTitle': 'Как стать постоянным',
        'analytics.howToBecomeRegularDesc': 'Выполнять задания на сайте минимум 3 раза',

        // Create Course Modal
        'course.enterTitle': 'Введите название курса',
        'course.created': 'Курс создан!',
        'course.failedToCreate': 'Не удалось создать курс',

        // Student pages
        'student.dashboard.greeting': 'Здравствуйте',
        'student.dashboard.student': 'ученик',
        'student.dashboard.selectSection': 'Выберите нужный раздел: задания или тесты.',
        'student.dashboard.myAssignments': 'Мои задания',
        'student.dashboard.myAssignmentsDesc': 'Загрузите файл и/или отправьте текстовый ответ по заданию учителя.',
        'student.dashboard.openAssignments': 'Открыть задания',
        'student.dashboard.myTests': 'Мои тесты',
        'student.dashboard.myTestsDesc': 'Пройдите тесты по кодам, которые выдал учитель.',
        'student.dashboard.openTests': 'Открыть тесты',
        'student.dashboard.myProgress': 'Мой прогресс',
        'student.dashboard.progressDesc': 'История попыток и аналитика будут отображаться здесь по мере выполнения заданий.',
        'student.progress.pageTitle': 'Подробный прогресс',
        'student.progress.pageSubtitle': 'Все попытки, динамика и разбор по типам заданий в одном месте.',
        'student.progress.attempts': 'Попытки',
        'student.progress.averageScore': 'Средний балл',
        'student.progress.bestScore': 'Лучший результат',
        'student.progress.inReview': 'На проверке',
        'student.progress.recentActivity': 'Последние попытки',
        'student.progress.quiz': 'Тест',
        'student.progress.assignment': 'Задание',
        'student.progress.submitted': 'Отправлено',
        'student.progress.graded': 'Проверено',
        'student.progress.reviewed': 'Проверено',
        'student.progress.noActivity': 'Пока нет попыток. Пройдите тест или отправьте задание, чтобы увидеть прогресс.',
        'student.progress.completed': 'Завершено',
        'student.progress.all': 'Все',
        'student.progress.quizOnly': 'Тесты',
        'student.progress.assignmentOnly': 'Задания',
        'student.progress.summary': 'Сводка',
        'student.progress.timeline': 'Хронология попыток',
        'student.progress.typeBreakdown': 'Разбор по типам',
        'student.progress.completedAttempts': 'Завершённые попытки',
        'student.progress.completedCount': 'Завершено',
        'student.progress.quizCount': 'Тестов',
        'student.progress.assignmentCount': 'Заданий',
        'student.progress.statusSubmitted': 'Отправлено',
        'student.progress.statusReviewed': 'Проверено',
        'student.progress.openDetailed': 'Открыть подробный раздел',
        'student.progress.emptyTitle': 'Пока нет истории прогресса',
        'student.progress.emptyDesc': 'Пройдите тест или отправьте задание, чтобы увидеть подробную аналитику.',
        'student.progress.scoreLabel': 'Баллы',
        'student.progress.filterHint': 'Фильтр по типу попытки',
        'student.tests.title': 'Тесты ученика',
        'student.tests.greeting': 'Здравствуйте',
        'student.tests.description': 'Здесь вы проходите тесты по кодам от учителя.',
        'student.tests.openByCode': 'Открыть тест по коду',
        'student.tests.enterCode': 'Введите код теста',
        'student.tests.open': 'Открыть',
        'student.tests.continueLastTest': 'Продолжить последний тест',
        'student.tests.enterTestCode': 'Введите код теста',
        'student.tests.checkCode': 'Проверьте код из ссылки учителя',
        'student.assignments.title': 'Задания ученика',
        'student.assignments.description': 'Здесь собраны ваши задания с возможностью отправить файл и/или текстовый ответ.',
        'student.assignments.openByCode': 'Открыть задание по коду',
        'student.assignments.enterCode': 'Введите код задания',
        'student.assignments.continueLastAssignment': 'Продолжить последнее задание',
        'student.assignments.enterAssignmentCode': 'Введите код задания',
        'student.label': 'Ученик',

        // Shared Quiz
        'shared.student': 'Ученик',

        // OCR tooltips
        'ocr.zoomIn': 'Увеличить',
        'ocr.zoomOut': 'Уменьшить',

        // Analytics
        'analytics.regularStudent': 'Постоянный',

        // AI Workspace
        'ai.testKeyword': 'тест',

        // AI Workspace
        'ai.documentNotFound': 'Документ не найден',
        'ai.uploadFile': 'Загрузите файл для начала работы',
        'ai.selectMaterial': 'Выберите материал',
        'ai.noMaterials': 'Нет материалов',
        'ai.uploadFirst': 'Загрузите материал для начала работы',
        'ai.smartActions': 'Умные действия',
        'ai.saveToLibrary': 'Сохранить в библиотеку',
        'ai.share': 'Поделиться',
        'ai.print': 'Печать',
        'ai.presentationMode': 'Режим презентации',
        'ai.editMode': 'Режим редактирования',
        'ai.questionCount': 'вопросов',
        'ai.addQuestion': 'Добавить вопрос',
        'ai.deleteQuestion': 'Удалить вопрос',
        'ai.regenerate': 'Перегенерировать',
        'ai.questionText': 'Текст вопроса',
        'ai.options': 'Варианты ответа',
        'ai.correctAnswer': 'Правильный ответ',
        'ai.option': 'Вариант',
        'ai.loading': 'Загрузка...',
        'ai.error': 'Ошибка',
        'ai.tryAgain': 'Попробовать снова',
        'ai.saved': 'Сохранено',
        'ai.savedToLibrary': 'Тест сохранен в библиотеку',
        'ai.createCourse': 'Создать курс',
        'ai.selectCourse': 'Выберите курс',
        'ai.noCourse': 'Нет курса',
        'ai.selectCourseFirst': 'Сначала выберите курс в левом меню',
        'ai.materials': 'Материалы',
        'ai.quizBuilder': 'Конструктор тестов',
        'ai.chat': 'Чат',
        'ai.sessions': 'Сессии',
        'ai.newSession': 'Новая сессия',
        'ai.sendMessage': 'Отправить сообщение',
        'ai.typeMessage': 'Введите сообщение...',
        'ai.aiResponse': 'Ответ AI',
        'ai.userMessage': 'Ваше сообщение',
        'ai.generating.quiz': 'Генерация теста...',
        'ai.generating.summary': 'Генерация конспекта...',
        'ai.generating.response': 'Генерация ответа...',
        'ai.quickStart': 'Быстрый старт',
        'ai.templates': 'Шаблоны',
        'ai.customQuiz': 'Свой тест',
        'ai.questions': 'вопросов',
        'ai.minutes': 'минут',
        'ai.entryTest': 'Входное тестирование',
        'ai.entryTestDesc': '15 вопросов',
        'ai.quickQuiz': 'Квиз-пятиминутка',
        'ai.quickQuizDesc': '5 вопросов (T/F)',
        'ai.finalTest': 'Итоговая контрольная',
        'ai.finalTestDesc': '20 вопросов',
        'ai.analyzed': 'Я проанализировал документ',
        'ai.readyToWork': 'Готов ответить на вопросы или создать тест',
        'ai.loadedFromLibrary': 'Тест загружен из библиотеки',
        'ai.notFoundInLibrary': 'Не удалось найти тест в библиотеке',
        'ai.failedToLoad': 'Не удалось загрузить документ',
        'ai.errorContent': 'Не удалось загрузить содержимое',
        'ai.newSessionStarted': 'Начата новая сессия',
        'ai.sessionEmpty': 'Сессия пуста',
        'ai.failedToOpen': 'Не удалось открыть',
        'ai.failedToOpenSession': 'Не удалось открыть сессию',
        'ai.failedToOpenMaterial': 'Не удалось открыть материал',
        'ai.failedToPerformAction': 'Не удалось выполнить действие',
        'ai.actionCompleted': 'Действие выполнено',
        'ai.tryAgainLater': 'Попробуйте ещё раз',
        'ai.failedToConnect': 'Не удалось подключиться к серверу. Попробуйте чуть позже',
        'ai.messageReceived': 'Сообщение получено',
        'ai.incorrectResponse': 'Ошибка: некорректный ответ сервера',
        'ai.noCorrectMaterial': 'Не выбран корректный материал',
        'ai.quizGenerated': 'Тест успешно сгенерирован',
        'ai.failedToGenerate': 'Ошибка при генерации теста',
        'ai.regeneratingQuestion': 'Перегенерация вопроса...',
        'ai.questionUpdated': 'Вопрос обновлён',
        'ai.failedToUpdate': 'Не удалось обновить вопрос',
        'ai.notSavedOnServer': 'Этот тест пока не сохранён на сервере',
        'ai.changesSaved': 'Изменения теста сохранены',
        'ai.failedToSaveChanges': 'Не удалось сохранить изменения',
        'ai.noQuestionsToSave': 'Нет вопросов для сохранения',
        'ai.savedOnServer': 'Тест сохранён на сервере',
        'ai.failedToSaveOnServer': 'Не удалось сохранить тест на сервере',
        'ai.localDraft': 'Локальный черновик',
        'ai.closeEdit': 'Закрыть редактирование',
        'ai.edit': 'Редактировать',
        'ai.saveEdits': 'Сохранить правки',
        'ai.correct': 'Верный',
        'ai.generatedSuccessfully': 'Тест сгенерирован успешно',
        'ai.question': 'вопрос',
        'ai.questions2': 'вопроса',
        'ai.questions5': 'вопросов',
        'ai.openLibrary': 'Открыть библиотеку',
        'ai.preview': 'Предпросмотр',
        'ai.regenerateAgain': 'Сгенерировать заново',
        'ai.shareWithStudents': 'Поделиться с учениками',
        'ai.firstGenerateAndSave': 'Сначала сгенерируйте и сохраните тест',
        'ai.shareQuiz': 'Поделиться тестом',
        'ai.shareMaterial': 'заданием',
        'ai.shareResult': 'результатом',
        'ai.sharing': 'Вы делитесь',
        'ai.configureAccess': 'Настройте параметры доступа ниже',
        'ai.viewOnlyMode': 'Режим только просмотра',
        'ai.passwordProtection': 'Защита паролем (необязательно)',
        'ai.enterPassword': 'Укажите пароль доступа',
        'ai.linkExpiry': 'Срок действия ссылки',
        'ai.1hour': '1 час',
        'ai.24hours': '24 часа',
        'ai.7days': '7 дней',
        'ai.never': 'Никогда',
        'ai.createLink': 'Создать ссылку',
        'ai.linkReady': 'Ссылка готова!',
        'ai.anyoneWithLink': 'Любой, у кого есть эта ссылка',
        'ai.andPassword': '(и пароль)',
        'ai.canOpenResource': 'сможет открыть ресурс',
        'ai.linkCreated': 'Ссылка для учеников создана',
        'ai.failedToCreateLink': 'Не удалось создать ссылку',
        'ai.linkCopied': 'Ссылка скопирована',
        'ai.historyChats': 'История чатов',
        'ai.selectMaterialAbove': 'Выберите материал вверху, чтобы начать работу',
        'ai.quiz': 'Тест',

        // Dashboard
        'dash.createFirstCourse': 'Создайте свой первый курс',
        'dash.startWorking': 'Начните работу с платформой, создав курс для ваших студентов',
        'dash.createCourse': 'Создать курс',
        'dash.activeCourse': 'Активный курс',
        'dash.quickStart': 'Быстрый старт',
        'dash.noWorksToReview': 'Нет работ для проверки',
        'dash.failedToLoad': 'Не удалось загрузить данные',
        'dash.failedToLoadDashboard': 'Не удалось загрузить дашборд',
        'dash.searchPlaceholder': 'Поиск...',
        'dash.nothingFound': 'Ничего не найдено',
        'dash.generatingPDF': 'Генерация PDF отчета...',
        'dash.reportDownloaded': 'Отчет скачан успешно',
        'dash.filesUploaded': 'файла загружено',
        'dash.fileUploaded': 'файл загружен',
        'dash.successfully': 'успешно!',
        'dash.createTest': 'Создать тест',
        'dash.ready': 'Готово',
        'dash.selectCourseFirst': 'Сначала выберите курс',
        'dash.failedToUpload': 'Не удалось загрузить файл',
        'dash.awaitingReview': 'Ожидает проверки',
        'dash.worksInQueue': 'работ в очереди',
        'dash.averageScore': 'Средний балл',
        'dash.checkedAttempts': 'проверенных попыток',
        'dash.students': 'Учеников',
        'dash.activeInCourse': 'активны в этом курсе',

        // Assignments
        'assignments.title': 'Задания курса',
        'assignments.course': 'Курс',
        'assignments.selectCourseFirst': 'Сначала выберите курс в левом меню',
        'assignments.sourceMaterial': 'Материал-источник',
        'assignments.noMaterials': 'Нет материалов в курсе',
        'assignments.preferences': 'Пожелания к заданию (опционально)',
        'assignments.preferencesPlaceholder': 'Например: сделать задание для 9 класса, 20 минут',
        'assignments.generateWithAI': 'Сгенерировать задание с AI',
        'assignments.generating': 'Генерация...',
        'assignments.saveAssignment': 'Сохранить задание',
        'assignments.saving': 'Сохранение...',
        'assignments.assignToStudents': 'Назначить ученикам',
        'assignments.assignmentText': 'Текст задания',
        'assignments.generateOrEnter': 'Сгенерируйте задание через AI или введите текст вручную',
        'assignments.formattingSupport': 'Поддерживается форматирование: заголовки (#), жирный (**текст**), курсив (*текст*), списки (- пункт).',
        'assignments.heading': 'Заголовок',
        'assignments.subheading': 'Подзаголовок',
        'assignments.bold': 'Жирный',
        'assignments.italic': 'Курсив',
        'assignments.list': 'Список',
        'assignments.listItem': 'Пункт списка',
        'assignments.steps': 'Шаги',
        'assignments.step1': 'Шаг 1',
        'assignments.step2': 'Шаг 2',
        'assignments.historyOfAssignments': 'История назначений',
        'assignments.refresh': 'Обновить',
        'assignments.loading': 'Загрузка...',
        'assignments.noLinksYet': 'Пока нет созданных ссылок на задания',
        'assignments.code': 'Код',
        'assignments.openLink': 'Открыть ссылку',
        'assignments.historyOfChecked': 'История проверенных заданий',
        'assignments.noAnswersYet': 'Ответов по заданиям пока нет',
        'assignments.checked': 'Проверено',
        'assignments.onReview': 'На проверке',
        'assignments.openAnswer': 'Открыть ответ',
        'assignments.studentAnswer': 'Ответ ученика',
        'assignments.loadingAnswer': 'Загрузка ответа...',
        'assignments.failedToLoadAnswer': 'Не удалось загрузить детали ответа',
        'assignments.answerFile': 'Файл ответа',
        'assignments.noFile': 'нет файла',
        'assignments.selectMaterial': 'Выберите материал для генерации задания',
        'assignments.selectMaterialError': 'Выберите материал',
        'assignments.enterText': 'Введите текст задания перед сохранением',
        'assignments.generated': 'Задание сгенерировано',
        'assignments.failedToGenerate': 'Не удалось сгенерировать задание',
        'assignments.saved': 'Задание сохранено',
        'assignments.failedToSave': 'Не удалось сохранить задание',
        'assignments.failedToLoadMaterials': 'Не удалось загрузить материалы курса',
        'assignments.failedToLoadHistory': 'Не удалось загрузить историю заданий',
        'assignments.failedToOpenAnswer': 'Не удалось открыть ответ',
        'assignments.assignment': 'Задание',

        // Quiz Results
        'results.title': 'Результаты и дневник',
        'results.course': 'Курс',
        'results.notSelected': 'не выбран',
        'results.backToAI': 'Назад в AI',
        'results.resultsTab': 'Результаты',
        'results.journalTab': 'Дневник',
        'results.selectCourseFirst': 'Сначала выберите курс в левом меню',
        'results.filterPlaceholder': 'Фильтр по quizId (опционально)',
        'results.apply': 'Применить',
        'results.totalAttempts': 'Всего попыток',
        'results.averageScore': 'Средний балл',
        'results.currentFilter': 'Текущий фильтр',
        'results.allTests': 'Все тесты',
        'results.student': 'Ученик',
        'results.test': 'Тест',
        'results.score': 'Балл',
        'results.date': 'Дата',
        'results.loading': 'Загрузка...',
        'results.noResults': 'Пока нет отправленных результатов',
        'results.studentsInJournal': 'Учеников в дневнике',
        'results.regularStudents': 'Постоянные ученики',
        'results.attemptsInCourse': '3+ попытки в курсе',
        'results.courseAverageScore': 'Средний балл курса',
        'results.loadingJournal': 'Загрузка дневника...',
        'results.noJournalData': 'Нет данных для дневника',
        'results.regular': 'Постоянный',
        'results.attempts': 'Попыток',
        'results.average': 'Средний',
        'results.last': 'Последний',
        'results.attemptHistory': 'История попыток',
        'results.teacherComment': 'Комментарий учителя',
        'results.commentPlaceholder': 'Напишите рекомендации ученику...',
        'results.saveComment': 'Сохранить комментарий',
        'results.saving': 'Сохранение...',
        'results.graded': 'проверено',
        'results.onReview': 'на проверке',
        'results.failedToLoad': 'Не удалось загрузить результаты',
        'results.failedToLoadJournal': 'Не удалось загрузить дневник учеников',
        'results.commentSaved': 'Комментарий сохранён',
        'results.failedToSaveComment': 'Не удалось сохранить комментарий',

        // Library
        'library.title': 'Библиотека тестов',
        'library.courseTests': 'Тесты курса',
        'library.courseNotSelected': 'курс не выбран',
        'library.backToAI': 'Вернуться в AI',
        'library.selectCourse': 'Выберите курс',
        'library.selectCourseFirst': 'Сначала выберите курс в левом меню.',
        'library.empty': 'Пока пусто',
        'library.emptyDesc': 'Сгенерируйте тест в AI ассистенте и нажмите «Сохранить в библиотеку».',
        'library.goToAI': 'Перейти в AI ассистент',
        'library.test': 'Тест',
        'library.questions': 'вопросов',
        'library.open': 'Открыть',
        'library.delete': 'Удалить',
        'library.quizDeleted': 'Тест удалён из библиотеки',

        // Teacher Quiz Preview - additional
        'preview.share': 'Поделиться',
        'preview.results': 'Результаты',
        'preview.correct': 'Верный',
        'preview.correctAnswerPlaceholder': 'Правильный ответ',
        'preview.explanationPlaceholder': 'Пояснение для учителя',

        // Shared Quiz
        'shared.invalidCodeFormat': 'Неверный формат кода. Используйте код из ссылки учителя',
        'shared.passwordRequired': 'Требуется пароль для доступа к тесту',
        'shared.failedToLoadTest': 'Не удалось загрузить тест',
        'shared.enterNameBeforeSubmit': 'Введите имя перед отправкой',
        'shared.failedToSubmitAnswers': 'Не удалось отправить ответы',
        'shared.addFileOrText': 'Добавьте файл и/или текст ответа',
        'shared.answerSentSuccessfully': 'Ответ успешно отправлен учителю',
        'shared.failedToSendAnswer': 'Не удалось отправить ответ',
        'shared.unsupportedFileType': 'Неподдерживаемый тип файла. Разрешены: pdf, docx, txt и изображения',
        'shared.fileTooLarge': 'Файл слишком большой. Максимум 10MB',
        'shared.leave': 'Выйти',
        'shared.leaveConfirm': 'Вы уверены, что хотите выйти? Несохранённые данные будут потеряны.',
        'shared.leaveWarning': 'У вас есть несохранённые данные. Если вы покинете страницу, они будут потеряны.',

        // Onboarding
        'onboarding.createCourse': 'Создайте курс',
        'onboarding.createCourseDesc': 'Курс объединяет материалы и студентов. Выберите название, например \'Физика 10А\' или \'История 9Б\'.',
        'onboarding.uploadMaterial': 'Загрузите материал',
        'onboarding.uploadMaterialDesc': 'Загрузите PDF, DOCX или TXT файл с лекцией, которую хотите использовать для генерации тестов.',
        'onboarding.generateTest': 'Сгенерируйте тест',
        'onboarding.generateTestDesc': 'Перейдите в AI Ассистент и создайте тест автоматически. AI проанализирует материал и сформирует вопросы.',
        'onboarding.skip': 'Пропустить',
        'onboarding.next': 'Далее',
        'onboarding.startWorking': 'Начать работу',
        'onboarding.step': 'Шаг',
        'onboarding.of': 'из',

        // Create Course Modal
        'createCourse.title': 'Создать курс',
        'createCourse.courseName': 'Название курса',
        'createCourse.required': '*',
        'createCourse.namePlaceholder': 'Например: 9А класс - Математика',
        'createCourse.description': 'Описание (опционально)',
        'createCourse.descriptionPlaceholder': 'Краткое описание курса...',
        'createCourse.courseColor': 'Цвет курса',
        'createCourse.courseIcon': 'Иконка курса',
        'createCourse.preview': 'Предпросмотр',
        'createCourse.courseNameDefault': 'Название курса',
        'createCourse.cancel': 'Отмена',
        'createCourse.create': 'Создать',
        'createCourse.creating': 'Создание...',
        'createCourse.colors.blue': 'Синий',
        'createCourse.colors.purple': 'Пурпурный',
        'createCourse.colors.pink': 'Розовый',
        'createCourse.colors.red': 'Красный',
        'createCourse.colors.orange': 'Оранжевый',
        'createCourse.colors.yellow': 'Жёлтый',
        'createCourse.colors.green': 'Зелёный',
        'createCourse.colors.teal': 'Бирюзовый',
        'createCourse.colors.cyan': 'Голубой',
        'createCourse.colors.indigo': 'Индиго',
        'createCourse.icons.school': 'Школа',
        'createCourse.icons.menu_book': 'Книга',
        'createCourse.icons.science': 'Наука',
        'createCourse.icons.calculate': 'Математика',
        'createCourse.icons.language': 'Язык',
        'createCourse.icons.palette': 'Палитра',
        'createCourse.icons.fitness_center': 'Физкультура',
        'createCourse.icons.music_note': 'Музыка',
        'createCourse.icons.psychology': 'Психология',
        'createCourse.icons.computer': 'Компьютер',
    },
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.ocr': 'Grade Works',
        'nav.ai': 'AI Assistant',
        'nav.files': 'Files Library',
        'nav.library': 'Test Library',
        'nav.results': 'Results',
        'nav.analytics': 'Analytics',
        'nav.settings': 'Settings',
        'nav.support': 'Support',
        'nav.logout': 'Logout',
        'nav.tools': 'Teacher Tools',
        'nav.saved': 'saved with AI',
        'nav.myDashboard': 'My Dashboard',
        'nav.myProgress': 'My Progress',
        'nav.myAssignments': 'My Assignments',
        'nav.myTests': 'My Tests',
        'nav.assignments': 'Assignments',
        'nav.studentDashboard': 'Student Dashboard',
        'nav.loading': 'Loading...',
        'nav.noCourses': 'No courses',
        'nav.createCourse': 'Create course',

        'dash.welcome': 'Good morning',
        'dash.upload': 'Upload Material',
        'dash.check': 'Check Assignments',
        'dash.needsReview': 'Needs Review',
        'dash.viewAll': 'View All',
        'dash.performance': 'Class Performance',
        'dash.avgScore': 'Avg Score',
        'dash.activity': 'Recent Activity',
        'dash.search': 'Search materials...',
        'dash.export': 'Export',
        'dash.queue': 'Upload Queue',
        'dash.clear': 'Clear',
        
        'ocr.back': 'Back',
        'ocr.save': 'Save',
        'ocr.confirmAll': 'Confirm All',
        'ocr.unsaved': 'Unsaved',
        'ocr.accuracy': 'Accuracy',
        'ocr.selected': 'selected',
        'ocr.approveSelected': 'Approve Selected',
        'ocr.close': 'Close',
        'ocr.saveChanges': 'Save Changes',
        'ocr.th.student': 'Student',
        'ocr.th.subject': 'Subject',
        'ocr.th.accuracy': 'Accuracy',
        'ocr.th.status': 'Status',
        'ocr.th.actions': 'Actions',
        'ocr.review': 'Review',
        'ocr.grade': 'Grade',
        'ocr.caughtUp': 'All caught up! No works pending.',
        'ocr.allChecked': 'All checked!',
        'ocr.reviewMode': 'REVIEW',
        'ocr.autoRecognized': 'The system automatically recognized text from the images. Check accuracy and approve the grades.',
        'ocr.noSubject': 'No subject',
        'ocr.status.flagged': 'needs attention',
        'ocr.status.reviewing': 'under review',
        'ocr.conf.high': 'High Confidence',
        'ocr.conf.low': 'Low Confidence',

        'ai.typing': 'is typing...',
        'ai.ask': 'Ask AI',
        'ai.analysis': 'Analysis',
        'ai.history': 'Session History',
        'ai.newChat': 'New Chat',
        'ai.placeholder': 'Ask a question about the material...',
        'ai.tab.canvas': 'AI Canvas',
        'ai.tab.builder': 'Test Builder',
        'ai.actions': 'AI Actions',
        'ai.action.explain': 'Explain',
        'ai.action.simplify': 'Simplify',
        'ai.action.translate': 'Translate',
        'ai.difficulty': 'DIFFICULTY',
        'ai.count': 'COUNT',
        'ai.generate': 'Generate',
        'ai.generating': 'Generating...',
        'ai.explanation': 'Explanation',
        'ai.diff.easy': 'Easy',
        'ai.diff.medium': 'Medium',
        'ai.diff.hard': 'Hard',

        'analytics.title': 'Class Analytics',
        'analytics.subtitle': 'Deep dive into performance',
        'analytics.average': 'Class Average',
        'analytics.leaderboard': 'Leaderboard',
        'analytics.back': 'Back to Overview',
        'analytics.breakdown': 'Student Breakdown',

        'settings.title': 'Settings',
        'settings.subtitle': 'Manage profile and preferences',
        'settings.profile': 'Profile',
        'settings.name': 'Name',
        'settings.surname': 'Surname',
        'settings.email': 'Email',
        'settings.emailReports': 'Email Reports',
        'settings.notifications': 'Smart Notifications',
        'settings.language': 'Interface Language',
        'settings.demo': 'Demo Mode',
        'settings.demoDesc': 'Resetting will clear all local changes and restore mock data.',
        'settings.reset': 'Reset to Demo Data',
        'settings.save': 'Save',
        'settings.cancel': 'Cancel',

        'auth.register': 'Registration',
        'auth.createAccount': 'Create Account',
        'auth.firstName': 'First Name',
        'auth.lastName': 'Last Name',
        'auth.password': 'Password',
        'auth.alreadyHaveAccount': 'Already have an account?',
        'auth.login': 'Log in',
        'auth.join': 'Join',

        // Login
        'login.title': 'Login',
        'login.subtitle': 'Enter your credentials to access',
        'login.invalidEmail': 'Enter a valid email',
        'login.enterPassword': 'Enter password',
        'login.forgotPassword': 'Forgot password?',
        'login.welcome': 'Welcome!',
        'login.invalidCredentials': 'Invalid login or password',
        'login.noAccount': 'Don\'t have an account yet?',

        // Teacher Quiz Preview
        'preview.title': 'Test Preview',
        'preview.subtitle': 'Teacher mode: edit before sending to students.',
        'preview.backToAI': 'Back to AI',
        'preview.saveChanges': 'Save changes',
        'preview.saving': 'Saving...',
        'preview.quizTitle': 'Test title',
        'preview.test': 'Test',
        'preview.failedToLoad': 'Failed to load test',
        'preview.changesSaved': 'Changes saved',
        'preview.failedToSave': 'Failed to save changes',

        // Settings additional
        'settings.drawnAvatars': 'Drawn avatars',
        'settings.selectAvatar': 'Select avatar',
        'settings.importAvatar': 'Import avatar',
        'settings.failedToLoadProfile': 'Failed to load user profile',
        'settings.onlyImages': 'Only images can be imported',
        'settings.avatarImported': 'Avatar imported',
        'settings.failedToImportAvatar': 'Failed to import avatar',
        'settings.errorSaving': 'Error saving profile',

        // Register
        'register.validEmail': 'Please enter a valid work email',
        'register.passwordLength': 'Password must be at least 6 characters',
        'register.accountCreated': 'Account created successfully! Now log in.',

        // OCR
        'ocr.fileNotFound': 'File not found',
        'ocr.failedToLoadQueue': 'Failed to load OCR queue',
        'ocr.failedToLoadDetails': 'Failed to load work details',
        'ocr.batchFailed': 'Batch operation failed',
        'ocr.changesSaved': 'Changes saved',
        'ocr.failedToSave': 'Failed to save',

        // Materials Library
        'materials.linkCreated': 'Link and assignment code created',
        'materials.failedToCreateLink': 'Failed to create assignment link',
        'materials.codeCopied': 'Code copied',
        'materials.linkCopied': 'Link copied',
        'materials.title': 'Files Library',
        'materials.courseFiles': 'Course files',
        'materials.backToDashboard': 'Back to dashboard',
        'materials.searchPlaceholder': 'Search material...',
        'materials.noCourseSelected': 'course not selected',
        'materials.selectCourseFirst': 'Select a course from the left menu first',
        'materials.loading': 'Loading...',
        'materials.notFound': 'Materials not found',
        'materials.publishedCount': 'Published assignments',
        'materials.clearLinks': 'Clear saved links',
        'materials.published': 'Assignment published',
        'materials.openAsStudent': 'Open as student',
        'materials.copyCode': 'Copy code',
        'materials.copyLink': 'Copy link',
        'materials.creating': 'Creating...',
        'materials.updateLink': 'Update link',
        'materials.createAssignment': 'Create assignment',
        'materials.openInAI': 'Open in AI',
        'materials.failedToLoad': 'Failed to load materials library',

        // Analytics
        'analytics.preparingPDF': 'Preparing PDF...',
        'analytics.reportReady': 'Report ready to print',
        'analytics.noCourseSelected': 'Choose a course to view analytics',
        'analytics.noDataTitle': 'No data to display',
        'analytics.noDataDesc': 'Upload materials and create tests',
        'analytics.exportPdf': 'Export PDF',
        'analytics.regularStudentsTitle': 'Regular students',
        'analytics.regularStudentsDesc': '3+ completed tests in the course',
        'analytics.activeStudentsTitle': 'Total active',
        'analytics.activeStudentsDesc': 'students with results',
        'analytics.howToBecomeRegularTitle': 'How to become regular',
        'analytics.howToBecomeRegularDesc': 'Complete assignments on the site at least 3 times',

        // Create Course Modal
        'course.enterTitle': 'Enter course title',
        'course.created': 'Course created!',
        'course.failedToCreate': 'Failed to create course',

        // Student pages
        'student.dashboard.greeting': 'Hello',
        'student.dashboard.student': 'student',
        'student.dashboard.selectSection': 'Select the section you need: assignments or tests.',
        'student.dashboard.myAssignments': 'My Assignments',
        'student.dashboard.myAssignmentsDesc': 'Upload a file and/or submit a text response to the teacher\'s assignment.',
        'student.dashboard.openAssignments': 'Open assignments',
        'student.dashboard.myTests': 'My Tests',
        'student.dashboard.myTestsDesc': 'Take tests using codes provided by the teacher.',
        'student.dashboard.openTests': 'Open tests',
        'student.dashboard.myProgress': 'My Progress',
        'student.dashboard.progressDesc': 'Attempt history and analytics will be displayed here as you complete assignments.',
        'student.progress.pageTitle': 'Detailed progress',
        'student.progress.pageSubtitle': 'All attempts, trends, and breakdowns by task type in one place.',
        'student.progress.attempts': 'Attempts',
        'student.progress.averageScore': 'Average score',
        'student.progress.bestScore': 'Best result',
        'student.progress.inReview': 'In review',
        'student.progress.recentActivity': 'Recent attempts',
        'student.progress.quiz': 'Quiz',
        'student.progress.assignment': 'Assignment',
        'student.progress.submitted': 'Submitted',
        'student.progress.graded': 'Checked',
        'student.progress.reviewed': 'Checked',
        'student.progress.noActivity': 'No attempts yet. Take a quiz or submit an assignment to see your progress.',
        'student.progress.completed': 'Completed',
        'student.progress.all': 'All',
        'student.progress.quizOnly': 'Quizzes',
        'student.progress.assignmentOnly': 'Assignments',
        'student.progress.summary': 'Summary',
        'student.progress.timeline': 'Attempt timeline',
        'student.progress.typeBreakdown': 'Type breakdown',
        'student.progress.completedAttempts': 'Completed attempts',
        'student.progress.completedCount': 'Completed',
        'student.progress.quizCount': 'Quizzes',
        'student.progress.assignmentCount': 'Assignments',
        'student.progress.statusSubmitted': 'Submitted',
        'student.progress.statusReviewed': 'Checked',
        'student.progress.openDetailed': 'Open detailed section',
        'student.progress.emptyTitle': 'No progress history yet',
        'student.progress.emptyDesc': 'Take a quiz or submit an assignment to see detailed analytics.',
        'student.progress.scoreLabel': 'Score',
        'student.progress.filterHint': 'Filter by attempt type',
        'student.tests.title': 'Student Tests',
        'student.tests.greeting': 'Hello',
        'student.tests.description': 'Here you take tests using codes from the teacher.',
        'student.tests.openByCode': 'Open test by code',
        'student.tests.enterCode': 'Enter test code',
        'student.tests.open': 'Open',
        'student.tests.continueLastTest': 'Continue last test',
        'student.tests.enterTestCode': 'Enter test code',
        'student.tests.checkCode': 'Check the code from the teacher\'s link',
        'student.assignments.title': 'Student Assignments',
        'student.assignments.description': 'Here are your assignments with the ability to submit a file and/or text response.',
        'student.assignments.openByCode': 'Open assignment by code',
        'student.assignments.enterCode': 'Enter assignment code',
        'student.assignments.continueLastAssignment': 'Continue last assignment',
        'student.assignments.enterAssignmentCode': 'Enter assignment code',
        'student.label': 'Student',

        // Shared Quiz
        'shared.student': 'Student',

        // OCR tooltips
        'ocr.zoomIn': 'Zoom in',
        'ocr.zoomOut': 'Zoom out',

        // Analytics
        'analytics.regularStudent': 'Regular',

        // AI Workspace
        'ai.testKeyword': 'test',

        // AI Workspace
        'ai.documentNotFound': 'Document not found',
        'ai.uploadFile': 'Upload a file to get started',
        'ai.selectMaterial': 'Select material',
        'ai.noMaterials': 'No materials',
        'ai.uploadFirst': 'Upload material to get started',
        'ai.smartActions': 'Smart Actions',
        'ai.saveToLibrary': 'Save to Library',
        'ai.share': 'Share',
        'ai.print': 'Print',
        'ai.presentationMode': 'Presentation Mode',
        'ai.editMode': 'Edit Mode',
        'ai.questionCount': 'questions',
        'ai.addQuestion': 'Add Question',
        'ai.deleteQuestion': 'Delete Question',
        'ai.regenerate': 'Regenerate',
        'ai.questionText': 'Question Text',
        'ai.options': 'Answer Options',
        'ai.correctAnswer': 'Correct Answer',
        'ai.option': 'Option',
        'ai.loading': 'Loading...',
        'ai.error': 'Error',
        'ai.tryAgain': 'Try Again',
        'ai.saved': 'Saved',
        'ai.savedToLibrary': 'Quiz saved to library',
        'ai.createCourse': 'Create Course',
        'ai.selectCourse': 'Select Course',
        'ai.noCourse': 'No Course',
        'ai.selectCourseFirst': 'Select a course from the left menu first',
        'ai.materials': 'Materials',
        'ai.quizBuilder': 'Quiz Builder',
        'ai.chat': 'Chat',
        'ai.sessions': 'Sessions',
        'ai.newSession': 'New Session',
        'ai.sendMessage': 'Send Message',
        'ai.typeMessage': 'Type a message...',
        'ai.aiResponse': 'AI Response',
        'ai.userMessage': 'Your Message',
        'ai.generating.quiz': 'Generating quiz...',
        'ai.generating.summary': 'Generating summary...',
        'ai.generating.response': 'Generating response...',
        'ai.quickStart': 'Quick Start',
        'ai.templates': 'Templates',
        'ai.customQuiz': 'Custom Quiz',
        'ai.questions': 'questions',
        'ai.minutes': 'minutes',
        'ai.entryTest': 'Entry Test',
        'ai.entryTestDesc': '15 questions',
        'ai.quickQuiz': 'Quick Quiz',
        'ai.quickQuizDesc': '5 questions (T/F)',
        'ai.finalTest': 'Final Test',
        'ai.finalTestDesc': '20 questions',
        'ai.analyzed': 'I analyzed the document',
        'ai.readyToWork': 'Ready to answer questions or create a test',
        'ai.loadedFromLibrary': 'Quiz loaded from library',
        'ai.notFoundInLibrary': 'Could not find quiz in library',
        'ai.failedToLoad': 'Failed to load document',
        'ai.errorContent': 'Failed to load content',
        'ai.newSessionStarted': 'New session started',
        'ai.sessionEmpty': 'Session is empty',
        'ai.failedToOpen': 'Failed to open',
        'ai.failedToOpenSession': 'Failed to open session',
        'ai.failedToOpenMaterial': 'Failed to open material',
        'ai.failedToPerformAction': 'Failed to perform action',
        'ai.actionCompleted': 'Action completed',
        'ai.tryAgainLater': 'Try again',
        'ai.failedToConnect': 'Failed to connect to server. Try again later',
        'ai.messageReceived': 'Message received',
        'ai.incorrectResponse': 'Error: incorrect server response',
        'ai.noCorrectMaterial': 'No correct material selected',
        'ai.quizGenerated': 'Quiz generated successfully',
        'ai.failedToGenerate': 'Error generating quiz',
        'ai.regeneratingQuestion': 'Regenerating question...',
        'ai.questionUpdated': 'Question updated',
        'ai.failedToUpdate': 'Failed to update question',
        'ai.notSavedOnServer': 'This quiz is not saved on server yet',
        'ai.changesSaved': 'Quiz changes saved',
        'ai.failedToSaveChanges': 'Failed to save changes',
        'ai.noQuestionsToSave': 'No questions to save',
        'ai.savedOnServer': 'Quiz saved on server',
        'ai.failedToSaveOnServer': 'Failed to save quiz on server',
        'ai.localDraft': 'Local draft',
        'ai.closeEdit': 'Close editing',
        'ai.edit': 'Edit',
        'ai.saveEdits': 'Save edits',
        'ai.correct': 'Correct',
        'ai.generatedSuccessfully': 'Quiz generated successfully',
        'ai.question': 'question',
        'ai.questions2': 'questions',
        'ai.questions5': 'questions',
        'ai.openLibrary': 'Open library',
        'ai.preview': 'Preview',
        'ai.regenerateAgain': 'Regenerate',
        'ai.shareWithStudents': 'Share with students',
        'ai.firstGenerateAndSave': 'First generate and save the quiz',
        'ai.shareQuiz': 'Share quiz',
        'ai.shareMaterial': 'assignment',
        'ai.shareResult': 'result',
        'ai.sharing': 'You are sharing',
        'ai.configureAccess': 'Configure access settings below',
        'ai.viewOnlyMode': 'View only mode',
        'ai.passwordProtection': 'Password protection (optional)',
        'ai.enterPassword': 'Enter access password',
        'ai.linkExpiry': 'Link expiry',
        'ai.1hour': '1 hour',
        'ai.24hours': '24 hours',
        'ai.7days': '7 days',
        'ai.never': 'Never',
        'ai.createLink': 'Create link',
        'ai.linkReady': 'Link ready!',
        'ai.anyoneWithLink': 'Anyone with this link',
        'ai.andPassword': '(and password)',
        'ai.canOpenResource': 'can open the resource',
        'ai.linkCreated': 'Student link created',
        'ai.failedToCreateLink': 'Failed to create link',
        'ai.linkCopied': 'Link copied',
        'ai.historyChats': 'Chat history',
        'ai.selectMaterialAbove': 'Select material above to get started',
        'ai.quiz': 'Quiz',

        // Dashboard
        'dash.createFirstCourse': 'Create your first course',
        'dash.startWorking': 'Start working with the platform by creating a course for your students',
        'dash.createCourse': 'Create course',
        'dash.activeCourse': 'Active course',
        'dash.quickStart': 'Quick Start',
        'dash.noWorksToReview': 'No works to review',
        'dash.failedToLoad': 'Failed to load data',
        'dash.failedToLoadDashboard': 'Failed to load dashboard',
        'dash.searchPlaceholder': 'Search...',
        'dash.nothingFound': 'Nothing found',
        'dash.generatingPDF': 'Generating PDF report...',
        'dash.reportDownloaded': 'Report downloaded successfully',
        'dash.filesUploaded': 'files uploaded',
        'dash.fileUploaded': 'file uploaded',
        'dash.successfully': 'successfully!',
        'dash.createTest': 'Create test',
        'dash.ready': 'Ready',
        'dash.selectCourseFirst': 'Select course first',
        'dash.failedToUpload': 'Failed to upload file',
        'dash.awaitingReview': 'Awaiting review',
        'dash.worksInQueue': 'works in queue',
        'dash.averageScore': 'Average score',
        'dash.checkedAttempts': 'checked attempts',
        'dash.students': 'Students',
        'dash.activeInCourse': 'active in this course',

        // Assignments
        'assignments.title': 'Course assignments',
        'assignments.course': 'Course',
        'assignments.selectCourseFirst': 'Select course from left menu first',
        'assignments.sourceMaterial': 'Source material',
        'assignments.noMaterials': 'No materials in course',
        'assignments.preferences': 'Assignment preferences (optional)',
        'assignments.preferencesPlaceholder': 'For example: make assignment for grade 9, 20 minutes',
        'assignments.generateWithAI': 'Generate assignment with AI',
        'assignments.generating': 'Generating...',
        'assignments.saveAssignment': 'Save assignment',
        'assignments.saving': 'Saving...',
        'assignments.assignToStudents': 'Assign to students',
        'assignments.assignmentText': 'Assignment text',
        'assignments.generateOrEnter': 'Generate assignment via AI or enter text manually',
        'assignments.formattingSupport': 'Formatting supported: headings (#), bold (**text**), italic (*text*), lists (- item).',
        'assignments.heading': 'Heading',
        'assignments.subheading': 'Subheading',
        'assignments.bold': 'Bold',
        'assignments.italic': 'Italic',
        'assignments.list': 'List',
        'assignments.listItem': 'List item',
        'assignments.steps': 'Steps',
        'assignments.step1': 'Step 1',
        'assignments.step2': 'Step 2',
        'assignments.historyOfAssignments': 'Assignment history',
        'assignments.refresh': 'Refresh',
        'assignments.loading': 'Loading...',
        'assignments.noLinksYet': 'No assignment links created yet',
        'assignments.code': 'Code',
        'assignments.openLink': 'Open link',
        'assignments.historyOfChecked': 'Checked assignments history',
        'assignments.noAnswersYet': 'No assignment answers yet',
        'assignments.checked': 'Checked',
        'assignments.onReview': 'On review',
        'assignments.openAnswer': 'Open answer',
        'assignments.studentAnswer': 'Student answer',
        'assignments.loadingAnswer': 'Loading answer...',
        'assignments.failedToLoadAnswer': 'Failed to load answer details',
        'assignments.answerFile': 'Answer file',
        'assignments.noFile': 'no file',
        'assignments.selectMaterial': 'Select material to generate assignment',
        'assignments.selectMaterialError': 'Select material',
        'assignments.enterText': 'Enter assignment text before saving',
        'assignments.generated': 'Assignment generated',
        'assignments.failedToGenerate': 'Failed to generate assignment',
        'assignments.saved': 'Assignment saved',
        'assignments.failedToSave': 'Failed to save assignment',
        'assignments.failedToLoadMaterials': 'Failed to load course materials',
        'assignments.failedToLoadHistory': 'Failed to load assignment history',
        'assignments.failedToOpenAnswer': 'Failed to open answer',
        'assignments.assignment': 'Assignment',

        // Quiz Results
        'results.title': 'Results and Journal',
        'results.course': 'Course',
        'results.notSelected': 'not selected',
        'results.backToAI': 'Back to AI',
        'results.resultsTab': 'Results',
        'results.journalTab': 'Journal',
        'results.selectCourseFirst': 'Select course from left menu first',
        'results.filterPlaceholder': 'Filter by quizId (optional)',
        'results.apply': 'Apply',
        'results.totalAttempts': 'Total attempts',
        'results.averageScore': 'Average score',
        'results.currentFilter': 'Current filter',
        'results.allTests': 'All tests',
        'results.student': 'Student',
        'results.test': 'Test',
        'results.score': 'Score',
        'results.date': 'Date',
        'results.loading': 'Loading...',
        'results.noResults': 'No submitted results yet',
        'results.studentsInJournal': 'Students in journal',
        'results.regularStudents': 'Regular students',
        'results.attemptsInCourse': '3+ attempts in course',
        'results.courseAverageScore': 'Course average score',
        'results.loadingJournal': 'Loading journal...',
        'results.noJournalData': 'No journal data',
        'results.regular': 'Regular',
        'results.attempts': 'Attempts',
        'results.average': 'Average',
        'results.last': 'Last',
        'results.attemptHistory': 'Attempt history',
        'results.teacherComment': 'Teacher comment',
        'results.commentPlaceholder': 'Write recommendations for the student...',
        'results.saveComment': 'Save comment',
        'results.saving': 'Saving...',
        'results.graded': 'graded',
        'results.onReview': 'on review',
        'results.failedToLoad': 'Failed to load results',
        'results.failedToLoadJournal': 'Failed to load student journal',
        'results.commentSaved': 'Comment saved',
        'results.failedToSaveComment': 'Failed to save comment',

        // Library
        'library.title': 'Test Library',
        'library.courseTests': 'Course tests',
        'library.courseNotSelected': 'course not selected',
        'library.backToAI': 'Back to AI',
        'library.selectCourse': 'Select course',
        'library.selectCourseFirst': 'Select course from left menu first.',
        'library.empty': 'Empty',
        'library.emptyDesc': 'Generate a test in AI assistant and click "Save to Library".',
        'library.goToAI': 'Go to AI assistant',
        'library.test': 'Test',
        'library.questions': 'questions',
        'library.open': 'Open',
        'library.delete': 'Delete',
        'library.quizDeleted': 'Test deleted from library',

        // Teacher Quiz Preview - additional
        'preview.share': 'Share',
        'preview.results': 'Results',
        'preview.correct': 'Correct',
        'preview.correctAnswerPlaceholder': 'Correct answer',
        'preview.explanationPlaceholder': 'Explanation for teacher',

        // Shared Quiz
        'shared.invalidCodeFormat': 'Invalid code format. Use code from teacher link',
        'shared.passwordRequired': 'Password required to access test',
        'shared.failedToLoadTest': 'Failed to load test',
        'shared.enterNameBeforeSubmit': 'Enter name before submitting',
        'shared.failedToSubmitAnswers': 'Failed to submit answers',
        'shared.addFileOrText': 'Add file and/or text answer',
        'shared.answerSentSuccessfully': 'Answer successfully sent to teacher',
        'shared.failedToSendAnswer': 'Failed to send answer',
        'shared.unsupportedFileType': 'Unsupported file type. Allowed: pdf, docx, txt and images',
        'shared.fileTooLarge': 'File too large. Maximum 10MB',
        'shared.leave': 'Leave',
        'shared.leaveConfirm': 'Are you sure you want to leave? Unsaved data will be lost.',
        'shared.leaveWarning': 'You have unsaved data. If you leave the page, it will be lost.',

        // Onboarding
        'onboarding.createCourse': 'Create a course',
        'onboarding.createCourseDesc': 'A course brings together materials and students. Choose a name, for example \'Physics 10A\' or \'History 9B\'.',
        'onboarding.uploadMaterial': 'Upload material',
        'onboarding.uploadMaterialDesc': 'Upload a PDF, DOCX or TXT file with a lecture you want to use for test generation.',
        'onboarding.generateTest': 'Generate a test',
        'onboarding.generateTestDesc': 'Go to AI Assistant and create a test automatically. AI will analyze the material and form questions.',
        'onboarding.skip': 'Skip',
        'onboarding.next': 'Next',
        'onboarding.startWorking': 'Start working',
        'onboarding.step': 'Step',
        'onboarding.of': 'of',

        // Create Course Modal
        'createCourse.title': 'Create course',
        'createCourse.courseName': 'Course name',
        'createCourse.required': '*',
        'createCourse.namePlaceholder': 'For example: Grade 9A - Mathematics',
        'createCourse.description': 'Description (optional)',
        'createCourse.descriptionPlaceholder': 'Brief course description...',
        'createCourse.courseColor': 'Course color',
        'createCourse.courseIcon': 'Course icon',
        'createCourse.preview': 'Preview',
        'createCourse.courseNameDefault': 'Course name',
        'createCourse.cancel': 'Cancel',
        'createCourse.create': 'Create',
        'createCourse.creating': 'Creating...',
        'createCourse.colors.blue': 'Blue',
        'createCourse.colors.purple': 'Purple',
        'createCourse.colors.pink': 'Pink',
        'createCourse.colors.red': 'Red',
        'createCourse.colors.orange': 'Orange',
        'createCourse.colors.yellow': 'Yellow',
        'createCourse.colors.green': 'Green',
        'createCourse.colors.teal': 'Teal',
        'createCourse.colors.cyan': 'Cyan',
        'createCourse.colors.indigo': 'Indigo',
        'createCourse.icons.school': 'School',
        'createCourse.icons.menu_book': 'Book',
        'createCourse.icons.science': 'Science',
        'createCourse.icons.calculate': 'Math',
        'createCourse.icons.language': 'Language',
        'createCourse.icons.palette': 'Palette',
        'createCourse.icons.fitness_center': 'Fitness',
        'createCourse.icons.music_note': 'Music',
        'createCourse.icons.psychology': 'Psychology',
        'createCourse.icons.computer': 'Computer',
    },
    kk: {
        'nav.dashboard': 'Басты бет',
        'nav.ocr': 'Жұмыстарды тексеру',
        'nav.ai': 'AI Көмекші',
        'nav.files': 'Файлдар кітапханасы',
        'nav.library': 'Тесттер кітапханасы',
        'nav.results': 'Нәтижелер',
        'nav.analytics': 'Аналитика',
        'nav.settings': 'Баптаулар',
        'nav.support': 'Қолдау',
        'nav.logout': 'Шығу',
        'nav.tools': 'Мұғалім құралдары',
        'nav.saved': 'AI арқылы үнемделді',
        'nav.myDashboard': 'Менің кабинетім',
        'nav.myProgress': 'Менің прогресім',
        'nav.myAssignments': 'Менің тапсырмаларым',
        'nav.myTests': 'Менің тесттерім',
        'nav.assignments': 'Тапсырмалар',
        'nav.studentDashboard': 'Студент кабинеті',
        'nav.loading': 'Жүктелуде...',
        'nav.noCourses': 'Курстар жоқ',
        'nav.createCourse': 'Курс жасау',
        
        'dash.welcome': 'Қайырлы таң',
        'dash.upload': 'Материал жүктеу',
        'dash.check': 'Жұмыстарды тексеру',
        'dash.needsReview': 'Тексеру қажет',
        'dash.viewAll': 'Барлығын көру',
        'dash.performance': 'Сынып үлгерімі',
        'dash.avgScore': 'Орташа балл',
        'dash.activity': 'Соңғы белсенділік',
        'dash.search': 'Материалдарды іздеу...',
        'dash.export': 'Экспорт',
        'dash.queue': 'Жүктеу кезегі',
        'dash.clear': 'Тазалау',
        
        'ocr.back': 'Артқа',
        'ocr.save': 'Сақтау',
        'ocr.confirmAll': 'Барлығын растау',
        'ocr.unsaved': 'Сақталмаған',
        'ocr.accuracy': 'Дәлдік',
        'ocr.selected': 'таңдалды',
        'ocr.approveSelected': 'Таңдалғандарды растау',
        'ocr.close': 'Жабу',
        'ocr.saveChanges': 'Өзгерістерді сақтау',
        'ocr.th.student': 'Студент',
        'ocr.th.subject': 'Пән',
        'ocr.th.accuracy': 'Дәлдік',
        'ocr.th.status': 'Мәртебе',
        'ocr.th.actions': 'Әрекеттер',
        'ocr.review': 'Тексеру',
        'ocr.grade': 'Баға',
        'ocr.caughtUp': 'Барлығы тексерілді! Күтіп тұрған жұмыстар жоқ.',
        'ocr.allChecked': 'Барлығы тексерілді!',
        'ocr.reviewMode': 'ТЕКСЕРУ',
        'ocr.autoRecognized': 'Жүйе суреттердегі мәтінді автоматты түрде таныды. Дәлдігін тексеріп, бағаларды растаңыз.',
        'ocr.noSubject': 'Пәнсіз',
        'ocr.status.flagged': 'назар аударуды қажет етеді',
        'ocr.status.reviewing': 'тексерілуде',
        'ocr.conf.high': 'Жоғары дәлдік',
        'ocr.conf.low': 'Төмен дәлдік',
        
        'ai.typing': 'теріп жатыр...',
        'ai.ask': 'AI-ден сұрау',
        'ai.analysis': 'Талдау',
        'ai.history': 'Сессиялар тарихы',
        'ai.newChat': 'Жаңа чат',
        'ai.placeholder': 'Материал бойынша сұрақ қойыңыз...',
        'ai.tab.canvas': 'AI Кенепі',
        'ai.tab.builder': 'Тест құрастырушы',
        'ai.actions': 'AI әрекеттері',
        'ai.action.explain': 'Түсіндіру',
        'ai.action.simplify': 'Жеңілдету',
        'ai.action.translate': 'Аудару',
        'ai.difficulty': 'ҚИЫНДЫҚ',
        'ai.count': 'САНЫ',
        'ai.generate': 'Генерациялау',
        'ai.generating': 'Генерациялануда...',
        'ai.explanation': 'Түсіндірме',
        'ai.diff.easy': 'Оңай',
        'ai.diff.medium': 'Орташа',
        'ai.diff.hard': 'Қиын',

        'analytics.title': 'Сынып аналитикасы',
        'analytics.subtitle': 'Үлгерімнің толық шолуы',
        'analytics.average': 'Орташа балл',
        'analytics.leaderboard': 'Оқушылар рейтингі',
        'analytics.back': 'Шолуға оралу',
        'analytics.breakdown': 'Оқушылар бойынша бөлу',

        'settings.title': 'Баптаулар',
        'settings.subtitle': 'Профиль мен баптауларды басқару',
        'settings.profile': 'Профиль',
        'settings.name': 'Аты',
        'settings.surname': 'Тегі',
        'settings.email': 'Email',
        'settings.emailReports': 'Email есептері',
        'settings.notifications': 'Ақылды хабарландырулар',
        'settings.language': 'Интерфейс тілі',
        'settings.demo': 'Демо режимі',
        'settings.demoDesc': 'Қалпына келтіру барлық жергілікті өзгерістерді тазалап, бастапқы деректерді қалпына келтіреді.',
        'settings.reset': 'Демо деректерге қалпына келтіру',
        'settings.save': 'Сақтау',
        'settings.cancel': 'Болдырмау',

        'auth.register': 'Тіркелу',
        'auth.createAccount': 'Аккаунт құру',
        'auth.firstName': 'Аты',
        'auth.lastName': 'Тегі',
        'auth.password': 'Құпия сөз',
        'auth.alreadyHaveAccount': 'Аккаунт бар ма?',
        'auth.login': 'Кіру',
        'auth.join': 'Қосылу',

        // Login
        'login.title': 'Жүйеге кіру',
        'login.subtitle': 'Қол жеткізу үшін деректеріңізді енгізіңіз',
        'login.invalidEmail': 'Дұрыс email енгізіңіз',
        'login.enterPassword': 'Құпия сөзді енгізіңіз',
        'login.forgotPassword': 'Құпия сөзді ұмыттыңыз ба?',
        'login.welcome': 'Қош келдіңіз!',
        'login.invalidCredentials': 'Қате логин немесе құпия сөз',
        'login.noAccount': 'Аккаунт жоқ па?',

        // Teacher Quiz Preview
        'preview.title': 'Тестті алдын ала қарау',
        'preview.subtitle': 'Мұғалім режимі: студенттерге жіберу алдында өңдеу.',
        'preview.backToAI': 'AI-ға оралу',
        'preview.saveChanges': 'Өзгерістерді сақтау',
        'preview.saving': 'Сақталуда...',
        'preview.quizTitle': 'Тест атауы',
        'preview.test': 'Тест',
        'preview.failedToLoad': 'Тестті жүктеу мүмкін болмады',
        'preview.changesSaved': 'Өзгерістер сақталды',
        'preview.failedToSave': 'Өзгерістерді сақтау мүмкін болмады',

        // Settings additional
        'settings.drawnAvatars': 'Салынған аватарлар',
        'settings.selectAvatar': 'Аватарды таңдау',
        'settings.importAvatar': 'Аватарды импорттау',
        'settings.failedToLoadProfile': 'Пайдаланушы профилін жүктеу мүмкін болмады',
        'settings.onlyImages': 'Тек суреттерді импорттауға болады',
        'settings.avatarImported': 'Аватар импортталды',
        'settings.failedToImportAvatar': 'Аватарды импорттау мүмкін болмады',
        'settings.errorSaving': 'Профильді сақтау қатесі',

        // Register
        'register.validEmail': 'Дұрыс жұмыс email енгізіңіз',
        'register.passwordLength': 'Құпия сөз кемінде 6 таңбадан тұруы керек',
        'register.accountCreated': 'Аккаунт сәтті жасалды! Енді кіріңіз.',

        // OCR
        'ocr.fileNotFound': 'Файл табылмады',
        'ocr.failedToLoadQueue': 'OCR кезегін жүктеу мүмкін болмады',
        'ocr.failedToLoadDetails': 'Жұмыс мәліметтерін жүктеу мүмкін болмады',
        'ocr.batchFailed': 'Топтық операция орындалмады',
        'ocr.changesSaved': 'Өзгерістер сақталды',
        'ocr.failedToSave': 'Сақтау мүмкін болмады',

        // Materials Library
        'materials.linkCreated': 'Сілтеме және тапсырма коды жасалды',
        'materials.failedToCreateLink': 'Тапсырма сілтемесін жасау мүмкін болмады',
        'materials.codeCopied': 'Код көшірілді',
        'materials.linkCopied': 'Сілтеме көшірілді',
        'materials.title': 'Файлдар кітапханасы',
        'materials.courseFiles': 'Курс файлдары',
        'materials.backToDashboard': 'Дашбордқа',
        'materials.searchPlaceholder': 'Материалды іздеу...',
        'materials.noCourseSelected': 'курс таңдалмаған',
        'materials.selectCourseFirst': 'Алдымен сол жақ мәзірден курсты таңдаңыз',
        'materials.loading': 'Жүктелуде...',
        'materials.notFound': 'Материалдар табылмады',
        'materials.publishedCount': 'Жарияланған тапсырмалар',
        'materials.clearLinks': 'Сақталған сілтемелерді тазалау',
        'materials.published': 'Тапсырма жарияланды',
        'materials.openAsStudent': 'Оқушы ретінде ашу',
        'materials.copyCode': 'Кодты көшіру',
        'materials.copyLink': 'Сілтемені көшіру',
        'materials.creating': 'Жасалуда...',
        'materials.updateLink': 'Сілтемені жаңарту',
        'materials.createAssignment': 'Тапсырма жасау',
        'materials.openInAI': 'AI-де ашу',
        'materials.failedToLoad': 'Материалдар кітапханасын жүктеу мүмкін болмады',

        // Analytics
        'analytics.preparingPDF': 'PDF дайындалуда...',
        'analytics.reportReady': 'Есеп басып шығаруға дайын',
        'analytics.noCourseSelected': 'Аналитиканы көру үшін курсты таңдаңыз',
        'analytics.noDataTitle': 'Көрсетуге дерек жоқ',
        'analytics.noDataDesc': 'Материалдарды жүктеп, тесттер жасаңыз',
        'analytics.exportPdf': 'PDF экспорттау',
        'analytics.regularStudentsTitle': 'Тұрақты оқушылар',
        'analytics.regularStudentsDesc': 'Курс бойынша 3+ аяқталған тест',
        'analytics.activeStudentsTitle': 'Барлығы белсенді',
        'analytics.activeStudentsDesc': 'нәтижелері бар оқушылар',
        'analytics.howToBecomeRegularTitle': 'Қалай тұрақты болуға болады',
        'analytics.howToBecomeRegularDesc': 'Сайтта тапсырмаларды кемінде 3 рет орындау',

        // Create Course Modal
        'course.enterTitle': 'Курс атауын енгізіңіз',
        'course.created': 'Курс жасалды!',
        'course.failedToCreate': 'Курс жасау мүмкін болмады',

        // Student pages
        'student.dashboard.greeting': 'Сәлеметсіз бе',
        'student.dashboard.student': 'оқушы',
        'student.dashboard.selectSection': 'Қажетті бөлімді таңдаңыз: тапсырмалар немесе тесттер.',
        'student.dashboard.myAssignments': 'Менің тапсырмаларым',
        'student.dashboard.myAssignmentsDesc': 'Файл жүктеңіз және/немесе мұғалімнің тапсырмасына мәтіндік жауап жіберіңіз.',
        'student.dashboard.openAssignments': 'Тапсырмаларды ашу',
        'student.dashboard.myTests': 'Менің тесттерім',
        'student.dashboard.myTestsDesc': 'Мұғалім берген кодтар бойынша тесттерден өтіңіз.',
        'student.dashboard.openTests': 'Тесттерді ашу',
        'student.dashboard.myProgress': 'Менің прогресім',
        'student.dashboard.progressDesc': 'Әрекеттер тарихы және аналитика тапсырмаларды орындау барысында осында көрсетіледі.',
        'student.progress.pageTitle': 'Толық прогресс',
        'student.progress.pageSubtitle': 'Барлық әрекеттер, динамика және тапсырма түрлері бойынша талдау бір жерде.',
        'student.progress.attempts': 'Әрекеттер',
        'student.progress.averageScore': 'Орташа балл',
        'student.progress.bestScore': 'Ең жақсы нәтиже',
        'student.progress.inReview': 'Тексерілуде',
        'student.progress.recentActivity': 'Соңғы әрекеттер',
        'student.progress.quiz': 'Тест',
        'student.progress.assignment': 'Тапсырма',
        'student.progress.submitted': 'Жіберілді',
        'student.progress.graded': 'Тексерілді',
        'student.progress.reviewed': 'Тексерілді',
        'student.progress.noActivity': 'Әзірге әрекет жоқ. Прогресті көру үшін тест тапсырыңыз немесе тапсырма жіберіңіз.',
        'student.progress.completed': 'Аяқталды',
        'student.progress.all': 'Барлығы',
        'student.progress.quizOnly': 'Тесттер',
        'student.progress.assignmentOnly': 'Тапсырмалар',
        'student.progress.summary': 'Қорытынды',
        'student.progress.timeline': 'Әрекеттер хронологиясы',
        'student.progress.typeBreakdown': 'Түрлер бойынша талдау',
        'student.progress.completedAttempts': 'Аяқталған әрекеттер',
        'student.progress.completedCount': 'Аяқталды',
        'student.progress.quizCount': 'Тесттер',
        'student.progress.assignmentCount': 'Тапсырмалар',
        'student.progress.statusSubmitted': 'Жіберілді',
        'student.progress.statusReviewed': 'Тексерілді',
        'student.progress.openDetailed': 'Толық бөлімді ашу',
        'student.progress.emptyTitle': 'Әзірге прогресс тарихы жоқ',
        'student.progress.emptyDesc': 'Толық аналитиканы көру үшін тест тапсырыңыз немесе тапсырма жіберіңіз.',
        'student.progress.scoreLabel': 'Балл',
        'student.progress.filterHint': 'Әрекет түрі бойынша сүзгі',
        'student.tests.title': 'Оқушы тесттері',
        'student.tests.greeting': 'Сәлеметсіз бе',
        'student.tests.description': 'Мұнда сіз мұғалімнің кодтары бойынша тесттерден өтесіз.',
        'student.tests.openByCode': 'Код бойынша тестті ашу',
        'student.tests.enterCode': 'Тест кодын енгізіңіз',
        'student.tests.open': 'Ашу',
        'student.tests.continueLastTest': 'Соңғы тестті жалғастыру',
        'student.tests.enterTestCode': 'Тест кодын енгізіңіз',
        'student.tests.checkCode': 'Мұғалімнің сілтемесінен кодты тексеріңіз',
        'student.assignments.title': 'Оқушы тапсырмалары',
        'student.assignments.description': 'Мұнда файл және/немесе мәтіндік жауап жіберу мүмкіндігі бар тапсырмаларыңыз жиналған.',
        'student.assignments.openByCode': 'Код бойынша тапсырманы ашу',
        'student.assignments.enterCode': 'Тапсырма кодын енгізіңіз',
        'student.assignments.continueLastAssignment': 'Соңғы тапсырманы жалғастыру',
        'student.assignments.enterAssignmentCode': 'Тапсырма кодын енгізіңіз',
        'student.label': 'Оқушы',

        // Shared Quiz
        'shared.student': 'Оқушы',

        // OCR tooltips
        'ocr.zoomIn': 'Үлкейту',
        'ocr.zoomOut': 'Кішірейту',

        // Analytics
        'analytics.regularStudent': 'Тұрақты',

        // AI Workspace
        'ai.testKeyword': 'тест',

        // AI Workspace
        'ai.documentNotFound': 'Құжат табылмады',
        'ai.uploadFile': 'Жұмысты бастау үшін файл жүктеңіз',
        'ai.selectMaterial': 'Материалды таңдаңыз',
        'ai.noMaterials': 'Материалдар жоқ',
        'ai.uploadFirst': 'Жұмысты бастау үшін материал жүктеңіз',
        'ai.smartActions': 'Ақылды әрекеттер',
        'ai.saveToLibrary': 'Кітапханаға сақтау',
        'ai.share': 'Бөлісу',
        'ai.print': 'Басып шығару',
        'ai.presentationMode': 'Презентация режимі',
        'ai.editMode': 'Өңдеу режимі',
        'ai.questionCount': 'сұрақтар',
        'ai.addQuestion': 'Сұрақ қосу',
        'ai.deleteQuestion': 'Сұрақты жою',
        'ai.regenerate': 'Қайта генерациялау',
        'ai.questionText': 'Сұрақ мәтіні',
        'ai.options': 'Жауап нұсқалары',
        'ai.correctAnswer': 'Дұрыс жауап',
        'ai.option': 'Нұсқа',
        'ai.loading': 'Жүктелуде...',
        'ai.error': 'Қате',
        'ai.tryAgain': 'Қайталап көру',
        'ai.saved': 'Сақталды',
        'ai.savedToLibrary': 'Тест кітапханаға сақталды',
        'ai.createCourse': 'Курс құру',
        'ai.selectCourse': 'Курсты таңдаңыз',
        'ai.noCourse': 'Курс жоқ',
        'ai.selectCourseFirst': 'Алдымен сол жақ мәзірден курсты таңдаңыз',
        'ai.materials': 'Материалдар',
        'ai.quizBuilder': 'Тест құрастырушы',
        'ai.chat': 'Чат',
        'ai.sessions': 'Сессиялар',
        'ai.newSession': 'Жаңа сессия',
        'ai.sendMessage': 'Хабарлама жіберу',
        'ai.typeMessage': 'Хабарлама теріңіз...',
        'ai.aiResponse': 'AI жауабы',
        'ai.userMessage': 'Сіздің хабарламаңыз',
        'ai.generating.quiz': 'Тест генерацияланып жатыр...',
        'ai.generating.summary': 'Конспект генерацияланып жатыр...',
        'ai.generating.response': 'Жауап генерацияланып жатыр...',
        'ai.quickStart': 'Жылдам бастау',
        'ai.templates': 'Үлгілер',
        'ai.customQuiz': 'Өз тестім',
        'ai.questions': 'сұрақтар',
        'ai.minutes': 'минут',
        'ai.entryTest': 'Кіріс тестілеу',
        'ai.entryTestDesc': '15 сұрақ',
        'ai.quickQuiz': 'Бес минуттық квиз',
        'ai.quickQuizDesc': '5 сұрақ (Иә/Жоқ)',
        'ai.finalTest': 'Қорытынды бақылау',
        'ai.finalTestDesc': '20 сұрақ',
        'ai.analyzed': 'Мен құжатты талдадым',
        'ai.readyToWork': 'Сұрақтарға жауап беруге немесе тест жасауға дайынмын',
        'ai.loadedFromLibrary': 'Тест кітапханадан жүктелді',
        'ai.notFoundInLibrary': 'Кітапханада тест табылмады',
        'ai.failedToLoad': 'Құжатты жүктеу мүмкін болмады',
        'ai.errorContent': 'Мазмұнды жүктеу мүмкін болмады',
        'ai.newSessionStarted': 'Жаңа сессия басталды',
        'ai.sessionEmpty': 'Сессия бос',
        'ai.failedToOpen': 'Ашу мүмкін болмады',
        'ai.failedToOpenSession': 'Сессияны ашу мүмкін болмады',
        'ai.failedToOpenMaterial': 'Материалды ашу мүмкін болмады',
        'ai.failedToPerformAction': 'Әрекетті орындау мүмкін болмады',
        'ai.actionCompleted': 'Әрекет орындалды',
        'ai.tryAgainLater': 'Қайталап көріңіз',
        'ai.failedToConnect': 'Серверге қосылу мүмкін болмады. Кейінірек қайталап көріңіз',
        'ai.messageReceived': 'Хабарлама алынды',
        'ai.incorrectResponse': 'Қате: сервердің дұрыс емес жауабы',
        'ai.noCorrectMaterial': 'Дұрыс материал таңдалмаған',
        'ai.quizGenerated': 'Тест сәтті генерацияланды',
        'ai.failedToGenerate': 'Тестті генерациялау қатесі',
        'ai.regeneratingQuestion': 'Сұрақ қайта генерацияланып жатыр...',
        'ai.questionUpdated': 'Сұрақ жаңартылды',
        'ai.failedToUpdate': 'Сұрақты жаңарту мүмкін болмады',
        'ai.notSavedOnServer': 'Бұл тест әлі серверде сақталмаған',
        'ai.changesSaved': 'Тест өзгерістері сақталды',
        'ai.failedToSaveChanges': 'Өзгерістерді сақтау мүмкін болмады',
        'ai.noQuestionsToSave': 'Сақтауға сұрақтар жоқ',
        'ai.savedOnServer': 'Тест серверде сақталды',
        'ai.failedToSaveOnServer': 'Тестті серверде сақтау мүмкін болмады',
        'ai.localDraft': 'Жергілікті жоба',
        'ai.closeEdit': 'Өңдеуді жабу',
        'ai.edit': 'Өңдеу',
        'ai.saveEdits': 'Өзгерістерді сақтау',
        'ai.correct': 'Дұрыс',
        'ai.generatedSuccessfully': 'Тест сәтті генерацияланды',
        'ai.question': 'сұрақ',
        'ai.questions2': 'сұрақ',
        'ai.questions5': 'сұрақ',
        'ai.openLibrary': 'Кітапхананы ашу',
        'ai.preview': 'Алдын ала қарау',
        'ai.regenerateAgain': 'Қайта генерациялау',
        'ai.shareWithStudents': 'Оқушылармен бөлісу',
        'ai.firstGenerateAndSave': 'Алдымен тестті генерациялаңыз және сақтаңыз',
        'ai.shareQuiz': 'Тестпен бөлісу',
        'ai.shareMaterial': 'тапсырмамен',
        'ai.shareResult': 'нәтижемен',
        'ai.sharing': 'Сіз бөлісіп жатырсыз',
        'ai.configureAccess': 'Төменде қол жеткізу параметрлерін баптаңыз',
        'ai.viewOnlyMode': 'Тек қарау режимі',
        'ai.passwordProtection': 'Құпия сөзбен қорғау (міндетті емес)',
        'ai.enterPassword': 'Қол жеткізу құпия сөзін енгізіңіз',
        'ai.linkExpiry': 'Сілтеме мерзімі',
        'ai.1hour': '1 сағат',
        'ai.24hours': '24 сағат',
        'ai.7days': '7 күн',
        'ai.never': 'Ешқашан',
        'ai.createLink': 'Сілтеме жасау',
        'ai.linkReady': 'Сілтеме дайын!',
        'ai.anyoneWithLink': 'Бұл сілтемесі бар кез келген адам',
        'ai.andPassword': '(және құпия сөз)',
        'ai.canOpenResource': 'ресурсты аша алады',
        'ai.linkCreated': 'Оқушылар үшін сілтеме жасалды',
        'ai.failedToCreateLink': 'Сілтеме жасау мүмкін болмады',
        'ai.linkCopied': 'Сілтеме көшірілді',
        'ai.historyChats': 'Чат тарихы',
        'ai.selectMaterialAbove': 'Жұмысты бастау үшін жоғарыдан материалды таңдаңыз',
        'ai.quiz': 'Тест',

        // Dashboard
        'dash.createFirstCourse': 'Алғашқы курсыңызды жасаңыз',
        'dash.startWorking': 'Студенттеріңіз үшін курс жасау арқылы платформамен жұмысты бастаңыз',
        'dash.createCourse': 'Курс жасау',
        'dash.activeCourse': 'Белсенді курс',
        'dash.quickStart': 'Жылдам бастау',
        'dash.noWorksToReview': 'Тексеруге жұмыстар жоқ',
        'dash.failedToLoad': 'Деректерді жүктеу мүмкін болмады',
        'dash.failedToLoadDashboard': 'Басты бетті жүктеу мүмкін болмады',
        'dash.searchPlaceholder': 'Іздеу...',
        'dash.nothingFound': 'Ештеңе табылмады',
        'dash.generatingPDF': 'PDF есебі генерацияланып жатыр...',
        'dash.reportDownloaded': 'Есеп сәтті жүктелді',
        'dash.filesUploaded': 'файл жүктелді',
        'dash.fileUploaded': 'файл жүктелді',
        'dash.successfully': 'сәтті!',
        'dash.createTest': 'Тест жасау',
        'dash.ready': 'Дайын',
        'dash.selectCourseFirst': 'Алдымен курсты таңдаңыз',
        'dash.failedToUpload': 'Файлды жүктеу мүмкін болмады',
        'dash.awaitingReview': 'Тексеруді күтуде',
        'dash.worksInQueue': 'кезектегі жұмыстар',
        'dash.averageScore': 'Орташа балл',
        'dash.checkedAttempts': 'тексерілген әрекеттер',
        'dash.students': 'Студенттер',
        'dash.activeInCourse': 'бұл курста белсенді',

        // Assignments
        'assignments.title': 'Курс тапсырмалары',
        'assignments.course': 'Курс',
        'assignments.selectCourseFirst': 'Алдымен сол жақ мәзірден курсты таңдаңыз',
        'assignments.sourceMaterial': 'Бастапқы материал',
        'assignments.noMaterials': 'Курста материалдар жоқ',
        'assignments.preferences': 'Тапсырмаға тілектер (міндетті емес)',
        'assignments.preferencesPlaceholder': 'Мысалы: 9-сыныпқа тапсырма жасау, 20 минут',
        'assignments.generateWithAI': 'AI арқылы тапсырма генерациялау',
        'assignments.generating': 'Генерациялануда...',
        'assignments.saveAssignment': 'Тапсырманы сақтау',
        'assignments.saving': 'Сақталуда...',
        'assignments.assignToStudents': 'Оқушыларға тағайындау',
        'assignments.assignmentText': 'Тапсырма мәтіні',
        'assignments.generateOrEnter': 'AI арқылы тапсырма генерациялаңыз немесе мәтінді қолмен енгізіңіз',
        'assignments.formattingSupport': 'Пішімдеу қолдау көрсетіледі: тақырыптар (#), қалың (**мәтін**), курсив (*мәтін*), тізімдер (- элемент).',
        'assignments.heading': 'Тақырып',
        'assignments.subheading': 'Қосалқы тақырып',
        'assignments.bold': 'Қалың',
        'assignments.italic': 'Курсив',
        'assignments.list': 'Тізім',
        'assignments.listItem': 'Тізім элементі',
        'assignments.steps': 'Қадамдар',
        'assignments.step1': 'Қадам 1',
        'assignments.step2': 'Қадам 2',
        'assignments.historyOfAssignments': 'Тапсырмалар тарихы',
        'assignments.refresh': 'Жаңарту',
        'assignments.loading': 'Жүктелуде...',
        'assignments.noLinksYet': 'Тапсырмаларға сілтемелер әлі жасалмаған',
        'assignments.code': 'Код',
        'assignments.openLink': 'Сілтемені ашу',
        'assignments.historyOfChecked': 'Тексерілген тапсырмалар тарихы',
        'assignments.noAnswersYet': 'Тапсырмаларға жауаптар әлі жоқ',
        'assignments.checked': 'Тексерілді',
        'assignments.onReview': 'Тексеруде',
        'assignments.openAnswer': 'Жауапты ашу',
        'assignments.studentAnswer': 'Студент жауабы',
        'assignments.loadingAnswer': 'Жауап жүктелуде...',
        'assignments.failedToLoadAnswer': 'Жауап мәліметтерін жүктеу мүмкін болмады',
        'assignments.answerFile': 'Жауап файлы',
        'assignments.noFile': 'файл жоқ',
        'assignments.selectMaterial': 'Тапсырма генерациялау үшін материалды таңдаңыз',
        'assignments.selectMaterialError': 'Материалды таңдаңыз',
        'assignments.enterText': 'Сақтаудан бұрын тапсырма мәтінін енгізіңіз',
        'assignments.generated': 'Тапсырма генерацияланды',
        'assignments.failedToGenerate': 'Тапсырманы генерациялау мүмкін болмады',
        'assignments.saved': 'Тапсырма сақталды',
        'assignments.failedToSave': 'Тапсырманы сақтау мүмкін болмады',
        'assignments.failedToLoadMaterials': 'Курс материалдарын жүктеу мүмкін болмады',
        'assignments.failedToLoadHistory': 'Тапсырмалар тарихын жүктеу мүмкін болмады',
        'assignments.failedToOpenAnswer': 'Жауапты ашу мүмкін болмады',
        'assignments.assignment': 'Тапсырма',

        // Quiz Results
        'results.title': 'Нәтижелер және күнделік',
        'results.course': 'Курс',
        'results.notSelected': 'таңдалмаған',
        'results.backToAI': 'AI-ға оралу',
        'results.resultsTab': 'Нәтижелер',
        'results.journalTab': 'Күнделік',
        'results.selectCourseFirst': 'Алдымен сол жақ мәзірден курсты таңдаңыз',
        'results.filterPlaceholder': 'quizId бойынша сүзгі (міндетті емес)',
        'results.apply': 'Қолдану',
        'results.totalAttempts': 'Барлық әрекеттер',
        'results.averageScore': 'Орташа балл',
        'results.currentFilter': 'Ағымдағы сүзгі',
        'results.allTests': 'Барлық тесттер',
        'results.student': 'Студент',
        'results.test': 'Тест',
        'results.score': 'Балл',
        'results.date': 'Күні',
        'results.loading': 'Жүктелуде...',
        'results.noResults': 'Жіберілген нәтижелер әлі жоқ',
        'results.studentsInJournal': 'Күнделіктегі студенттер',
        'results.regularStudents': 'Тұрақты студенттер',
        'results.attemptsInCourse': 'Курста 3+ әрекет',
        'results.courseAverageScore': 'Курстың орташа баллы',
        'results.loadingJournal': 'Күнделік жүктелуде...',
        'results.noJournalData': 'Күнделік деректері жоқ',
        'results.regular': 'Тұрақты',
        'results.attempts': 'Әрекеттер',
        'results.average': 'Орташа',
        'results.last': 'Соңғы',
        'results.attemptHistory': 'Әрекеттер тарихы',
        'results.teacherComment': 'Мұғалім пікірі',
        'results.commentPlaceholder': 'Студентке ұсыныстар жазыңыз...',
        'results.saveComment': 'Пікірді сақтау',
        'results.saving': 'Сақталуда...',
        'results.graded': 'тексерілді',
        'results.onReview': 'тексеруде',
        'results.failedToLoad': 'Нәтижелерді жүктеу мүмкін болмады',
        'results.failedToLoadJournal': 'Студенттер күнделігін жүктеу мүмкін болмады',
        'results.commentSaved': 'Пікір сақталды',
        'results.failedToSaveComment': 'Пікірді сақтау мүмкін болмады',

        // Library
        'library.title': 'Тесттер кітапханасы',
        'library.courseTests': 'Курс тесттері',
        'library.courseNotSelected': 'курс таңдалмаған',
        'library.backToAI': 'AI-ға оралу',
        'library.selectCourse': 'Курсты таңдаңыз',
        'library.selectCourseFirst': 'Алдымен сол жақ мәзірден курсты таңдаңыз.',
        'library.empty': 'Әлі бос',
        'library.emptyDesc': 'AI көмекшісінде тест генерациялаңыз және «Кітапханаға сақтау» түймесін басыңыз.',
        'library.goToAI': 'AI көмекшісіне өту',
        'library.test': 'Тест',
        'library.questions': 'сұрақтар',
        'library.open': 'Ашу',
        'library.delete': 'Жою',
        'library.quizDeleted': 'Тест кітапханадан жойылды',

        // Teacher Quiz Preview - additional
        'preview.share': 'Бөлісу',
        'preview.results': 'Нәтижелер',
        'preview.correct': 'Дұрыс',
        'preview.correctAnswerPlaceholder': 'Дұрыс жауап',
        'preview.explanationPlaceholder': 'Мұғалімге түсініктеме',

        // Shared Quiz
        'shared.invalidCodeFormat': 'Код форматы дұрыс емес. Мұғалім сілтемесінен кодты пайдаланыңыз',
        'shared.passwordRequired': 'Тестке қол жеткізу үшін құпия сөз қажет',
        'shared.failedToLoadTest': 'Тестті жүктеу мүмкін болмады',
        'shared.enterNameBeforeSubmit': 'Жіберу алдында атыңызды енгізіңіз',
        'shared.failedToSubmitAnswers': 'Жауаптарды жіберу мүмкін болмады',
        'shared.addFileOrText': 'Файл және/немесе мәтін жауабын қосыңыз',
        'shared.answerSentSuccessfully': 'Жауап мұғалімге сәтті жіберілді',
        'shared.failedToSendAnswer': 'Жауапты жіберу мүмкін болмады',
        'shared.unsupportedFileType': 'Қолдау көрсетілмейтін файл түрі. Рұқсат етілген: pdf, docx, txt және суреттер',
        'shared.fileTooLarge': 'Файл тым үлкен. Максимум 10MB',
        'shared.leave': 'Шығу',
        'shared.leaveConfirm': 'Шығуды қалайсыз ба? Сақталмаған деректер жоғалады.',
        'shared.leaveWarning': 'Сақталмаған деректер бар. Бетті тастасаңыз, олар жоғалады.',

        // Onboarding
        'onboarding.createCourse': 'Курс жасаңыз',
        'onboarding.createCourseDesc': 'Курс материалдар мен студенттерді біріктіреді. Атауын таңдаңыз, мысалы \'Физика 10А\' немесе \'Тарих 9Б\'.',
        'onboarding.uploadMaterial': 'Материал жүктеңіз',
        'onboarding.uploadMaterialDesc': 'Тест генерациялау үшін пайдаланғыңыз келетін дәрісі бар PDF, DOCX немесе TXT файлын жүктеңіз.',
        'onboarding.generateTest': 'Тест генерациялаңыз',
        'onboarding.generateTestDesc': 'AI көмекшісіне өтіп, тестті автоматты түрде жасаңыз. AI материалды талдап, сұрақтар құрастырады.',
        'onboarding.skip': 'Өткізіп жіберу',
        'onboarding.next': 'Келесі',
        'onboarding.startWorking': 'Жұмысты бастау',
        'onboarding.step': 'Қадам',
        'onboarding.of': 'ден',

        // Create Course Modal
        'createCourse.title': 'Курс жасау',
        'createCourse.courseName': 'Курс атауы',
        'createCourse.required': '*',
        'createCourse.namePlaceholder': 'Мысалы: 9А сынып - Математика',
        'createCourse.description': 'Сипаттама (міндетті емес)',
        'createCourse.descriptionPlaceholder': 'Курстың қысқаша сипаттамасы...',
        'createCourse.courseColor': 'Курс түсі',
        'createCourse.courseIcon': 'Курс белгішесі',
        'createCourse.preview': 'Алдын ала қарау',
        'createCourse.courseNameDefault': 'Курс атауы',
        'createCourse.cancel': 'Болдырмау',
        'createCourse.create': 'Жасау',
        'createCourse.creating': 'Жасалуда...',
        'createCourse.colors.blue': 'Көк',
        'createCourse.colors.purple': 'Күлгін',
        'createCourse.colors.pink': 'Қызғылт',
        'createCourse.colors.red': 'Қызыл',
        'createCourse.colors.orange': 'Қызғылт сары',
        'createCourse.colors.yellow': 'Сары',
        'createCourse.colors.green': 'Жасыл',
        'createCourse.colors.teal': 'Көгілдір',
        'createCourse.colors.cyan': 'Ашық көк',
        'createCourse.colors.indigo': 'Индиго',
        'createCourse.icons.school': 'Мектеп',
        'createCourse.icons.menu_book': 'Кітап',
        'createCourse.icons.science': 'Ғылым',
        'createCourse.icons.calculate': 'Математика',
        'createCourse.icons.language': 'Тіл',
        'createCourse.icons.palette': 'Палитра',
        'createCourse.icons.fitness_center': 'Дене шынықтыру',
        'createCourse.icons.music_note': 'Музыка',
        'createCourse.icons.psychology': 'Психология',
        'createCourse.icons.computer': 'Компьютер',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        return (localStorage.getItem('appLanguage') as Language) || 'ru';
    });

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = (key: string) => {
        const translation = translations[language][key];
        if (!translation) {
            if (process.env.NODE_ENV === 'development') {
                console.warn(`Missing translation key: "${key}" for language: "${language}"`);
            }
            return key;
        }
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};